### ISSUE TITLE
Main top dropdown 'Create a new' overview checklist

### ISSUE THREAD

**Issue by viktorsmari** [reflow-project/zenpub-client#36]
Related to #18 

The Wireframe maps the `Create a new...` dropdown like this:

- [x] Create a new community ->  Communities  (No changes)
- [x] Create a new Intent   [example](https://reflowos.dyne.org/docs/api_tour#publish-a-proposal-by-itself) 
- [x] Create a new Resource? -> Create a new `EconomicResource` [example](https://reflowos.dyne.org/docs/api_tour#conduct-an-economic-event-that-results-in-a-completely-new-resource)
- [ ] Create a new EconomicEvent on an `EconomicResource` (Should this be in the dropdown?) [example](https://reflowos.dyne.org/docs/api_tour#conduct-an-economic-event-on-an-existing-resource), [api](https://reflowos.dyne.org/api/economicevent.doc.html)

Are all of the above correct? 

EconomicResource: https://reflowos.dyne.org/api/economicresource.doc.html

![2021-04-06_18-22-43](https://user-images.githubusercontent.com/1689020/113744566-1cdfed00-9705-11eb-93d1-ec509ccce37b.png)
